import { useEffect, useState } from 'react';
import { useSearchParams } from 'react-router-dom';
import Navbar from '../../components/Navbar/Navbar';
import { libraryApi } from '../../services/api';
import styles from './Catalog.module.css';

const statuses = { want_to_read: 'Quero ler', reading: 'Lendo', read: 'Lido', abandoned: 'Abandonei' };

function Catalog() {
  const [params] = useSearchParams();
  const [query, setQuery] = useState(''); const [books, setBooks] = useState([]); const [shelves, setShelves] = useState([]);
  const [selected, setSelected] = useState(null); const [status, setStatus] = useState('want_to_read'); const [shelfIds, setShelfIds] = useState([]);
  const [newShelf, setNewShelf] = useState(''); const [loading, setLoading] = useState(false); const [message, setMessage] = useState('');
  useEffect(() => { libraryApi.shelves().then(setShelves).catch((error) => setMessage(error.message)); }, []);
  const search = async (event) => { event.preventDefault(); if (query.trim().length < 2) return setMessage('Digite pelo menos 2 caracteres para buscar.'); setLoading(true); setMessage(''); try { setBooks(await libraryApi.searchBooks(query)); } catch (error) { setMessage(error.message); } finally { setLoading(false); } };
  const chooseBook = (book) => { const requestedShelfId = params.get('shelfId'); setSelected(book); setStatus('want_to_read'); setShelfIds(requestedShelfId ? [requestedShelfId] : []); setMessage(''); };
  const createShelf = async () => { if (!newShelf.trim()) return; try { const shelf = await libraryApi.createShelf(newShelf); setShelves((items) => [...items, shelf].sort((a, b) => a.name.localeCompare(b.name))); setShelfIds((ids) => [...ids, shelf.id]); setNewShelf(''); } catch (error) { setMessage(error.message); } };
  const saveBook = async (event) => { event.preventDefault(); try { await libraryApi.addBook({ googleVolumeId: selected.googleVolumeId, status, shelfIds }); setMessage(`“${selected.title}” foi salvo na sua biblioteca.`); setSelected(null); } catch (error) { setMessage(error.message); } };
  return <><Navbar /><main className={styles.page}><header><p className={styles.eyebrow}>Catálogo</p><h1>Encontre sua próxima leitura</h1><p>Pesquise no Google Books e organize um título em quantas estantes quiser.</p></header><form className={styles.search} onSubmit={search}><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Título, autor ou ISBN" aria-label="Pesquisar livros" /><button disabled={loading}>{loading ? 'Buscando...' : 'Buscar'}</button></form>{message && <p className={styles.message}>{message}</p>}<section className={styles.results}>{books.map((book) => <article className={styles.card} key={book.googleVolumeId}><div className={styles.cover}>{book.thumbnailUrl ? <img src={book.thumbnailUrl} alt={`Capa de ${book.title}`} /> : <span>{book.title}</span>}</div><div><h2>{book.title}</h2><p>{book.authors.join(', ') || 'Autor não informado'}</p><small>{book.publishedDate || 'Data não informada'}</small><button className={styles.addButton} onClick={() => chooseBook(book)}>Adicionar às estantes</button></div></article>)}</section>{selected && <div className={styles.backdrop} role="presentation"><section className={styles.dialog} role="dialog" aria-modal="true" aria-labelledby="add-title"><button className={styles.close} onClick={() => setSelected(null)} aria-label="Fechar">×</button><p className={styles.eyebrow}>Adicionar à biblioteca</p><h2 id="add-title">{selected.title}</h2><form onSubmit={saveBook}><label>Status<select value={status} onChange={(event) => setStatus(event.target.value)}>{Object.entries(statuses).map(([value, label]) => <option value={value} key={value}>{label}</option>)}</select></label><fieldset><legend>Estantes</legend>{shelves.length === 0 && <p className={styles.empty}>Crie sua primeira estante abaixo.</p>}{shelves.map((shelf) => <label className={styles.check} key={shelf.id}><input type="checkbox" checked={shelfIds.includes(shelf.id)} onChange={() => setShelfIds((ids) => ids.includes(shelf.id) ? ids.filter((id) => id !== shelf.id) : [...ids, shelf.id])} />{shelf.name}</label>)}</fieldset><div className={styles.newShelf}><input value={newShelf} onChange={(event) => setNewShelf(event.target.value)} placeholder="Nova estante" /><button type="button" onClick={createShelf}>Criar</button></div><button className={styles.saveButton}>Salvar livro</button></form></section></div>}</main></>;
}
export default Catalog;
