import { MigrationInterface, QueryRunner } from 'typeorm';

export class CreateLibrary1720000000000 implements MigrationInterface {
  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query("CREATE TYPE \"reading_status\" AS ENUM ('read', 'reading', 'want_to_read', 'abandoned')");
    await queryRunner.query('CREATE TABLE "books" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "google_volume_id" varchar, "title" varchar NOT NULL, "normalized_title" varchar NOT NULL, "authors" jsonb NOT NULL DEFAULT \'[]\', "thumbnail_url" varchar, "published_date" varchar, "description" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_books" PRIMARY KEY ("id"), CONSTRAINT "UQ_books_google" UNIQUE ("google_volume_id"), CONSTRAINT "UQ_books_title" UNIQUE ("normalized_title"))');
    await queryRunner.query('CREATE TABLE "shelves" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "name" varchar(80) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_shelves" PRIMARY KEY ("id"), CONSTRAINT "UQ_shelves_user_name" UNIQUE ("user_id", "name"), CONSTRAINT "FK_shelves_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE)');
    await queryRunner.query('CREATE TABLE "user_books" ("id" uuid NOT NULL DEFAULT gen_random_uuid(), "user_id" uuid NOT NULL, "book_id" uuid NOT NULL, "status" "reading_status" NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_user_books" PRIMARY KEY ("id"), CONSTRAINT "UQ_user_books" UNIQUE ("user_id", "book_id"), CONSTRAINT "FK_user_books_user" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE, CONSTRAINT "FK_user_books_book" FOREIGN KEY ("book_id") REFERENCES "books"("id") ON DELETE CASCADE)');
    await queryRunner.query('CREATE TABLE "user_book_shelves" ("user_book_id" uuid NOT NULL, "shelf_id" uuid NOT NULL, CONSTRAINT "PK_user_book_shelves" PRIMARY KEY ("user_book_id", "shelf_id"), CONSTRAINT "FK_links_user_book" FOREIGN KEY ("user_book_id") REFERENCES "user_books"("id") ON DELETE CASCADE, CONSTRAINT "FK_links_shelf" FOREIGN KEY ("shelf_id") REFERENCES "shelves"("id") ON DELETE CASCADE)');
  }
  public async down(queryRunner: QueryRunner): Promise<void> { await queryRunner.query('DROP TABLE "user_book_shelves"'); await queryRunner.query('DROP TABLE "user_books"'); await queryRunner.query('DROP TABLE "shelves"'); await queryRunner.query('DROP TABLE "books"'); await queryRunner.query('DROP TYPE "reading_status"'); }
}
